/**
 * Food Delivery Platform API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec, HttpContext 
        }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from '../encoder';
import { Observable }                                        from 'rxjs';

// @ts-ignore
import { ApiV1DeliveriesAssignPost200Response } from '../model/apiV1DeliveriesAssignPost200Response';
// @ts-ignore
import { ApiV1DeliveriesAssignPostRequest } from '../model/apiV1DeliveriesAssignPostRequest';
// @ts-ignore
import { ApiV1DeliveriesDeliveryIdStatusPutRequest } from '../model/apiV1DeliveriesDeliveryIdStatusPutRequest';
// @ts-ignore
import { ApiV1DeliveriesGet200Response } from '../model/apiV1DeliveriesGet200Response';
// @ts-ignore
import { ApiV1OrdersOrderIdStatusPut200Response } from '../model/apiV1OrdersOrderIdStatusPut200Response';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import { BaseService } from '../api.base.service';



@Injectable({
  providedIn: 'root'
})
export class DeliveriesService extends BaseService {

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string|string[], @Optional() configuration?: Configuration) {
        super(basePath, configuration);
    }

    /**
     * Assign delivery
     * Assign an order to a delivery agent
     * @endpoint post /api/v1/deliveries/assign
     * @param apiV1DeliveriesAssignPostRequest 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiV1DeliveriesAssignPost(apiV1DeliveriesAssignPostRequest: ApiV1DeliveriesAssignPostRequest, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<ApiV1DeliveriesAssignPost200Response>;
    public apiV1DeliveriesAssignPost(apiV1DeliveriesAssignPostRequest: ApiV1DeliveriesAssignPostRequest, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<ApiV1DeliveriesAssignPost200Response>>;
    public apiV1DeliveriesAssignPost(apiV1DeliveriesAssignPostRequest: ApiV1DeliveriesAssignPostRequest, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<ApiV1DeliveriesAssignPost200Response>>;
    public apiV1DeliveriesAssignPost(apiV1DeliveriesAssignPostRequest: ApiV1DeliveriesAssignPostRequest, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (apiV1DeliveriesAssignPostRequest === null || apiV1DeliveriesAssignPostRequest === undefined) {
            throw new Error('Required parameter apiV1DeliveriesAssignPostRequest was null or undefined when calling apiV1DeliveriesAssignPost.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (bearerAuth) required
        localVarHeaders = this.configuration.addCredentialToHeaders('bearerAuth', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/v1/deliveries/assign`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<ApiV1DeliveriesAssignPost200Response>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: apiV1DeliveriesAssignPostRequest,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Update delivery status
     * Update the status of a delivery
     * @endpoint put /api/v1/deliveries/{deliveryId}/status
     * @param deliveryId 
     * @param apiV1DeliveriesDeliveryIdStatusPutRequest 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiV1DeliveriesDeliveryIdStatusPut(deliveryId: string, apiV1DeliveriesDeliveryIdStatusPutRequest: ApiV1DeliveriesDeliveryIdStatusPutRequest, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<ApiV1OrdersOrderIdStatusPut200Response>;
    public apiV1DeliveriesDeliveryIdStatusPut(deliveryId: string, apiV1DeliveriesDeliveryIdStatusPutRequest: ApiV1DeliveriesDeliveryIdStatusPutRequest, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<ApiV1OrdersOrderIdStatusPut200Response>>;
    public apiV1DeliveriesDeliveryIdStatusPut(deliveryId: string, apiV1DeliveriesDeliveryIdStatusPutRequest: ApiV1DeliveriesDeliveryIdStatusPutRequest, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<ApiV1OrdersOrderIdStatusPut200Response>>;
    public apiV1DeliveriesDeliveryIdStatusPut(deliveryId: string, apiV1DeliveriesDeliveryIdStatusPutRequest: ApiV1DeliveriesDeliveryIdStatusPutRequest, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (deliveryId === null || deliveryId === undefined) {
            throw new Error('Required parameter deliveryId was null or undefined when calling apiV1DeliveriesDeliveryIdStatusPut.');
        }
        if (apiV1DeliveriesDeliveryIdStatusPutRequest === null || apiV1DeliveriesDeliveryIdStatusPutRequest === undefined) {
            throw new Error('Required parameter apiV1DeliveriesDeliveryIdStatusPutRequest was null or undefined when calling apiV1DeliveriesDeliveryIdStatusPut.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (bearerAuth) required
        localVarHeaders = this.configuration.addCredentialToHeaders('bearerAuth', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/v1/deliveries/${this.configuration.encodeParam({name: "deliveryId", value: deliveryId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/status`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<ApiV1OrdersOrderIdStatusPut200Response>('put', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: apiV1DeliveriesDeliveryIdStatusPutRequest,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get deliveries
     * Get deliveries assigned to a delivery agent
     * @endpoint get /api/v1/deliveries
     * @param agentId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiV1DeliveriesGet(agentId: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<ApiV1DeliveriesGet200Response>;
    public apiV1DeliveriesGet(agentId: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<ApiV1DeliveriesGet200Response>>;
    public apiV1DeliveriesGet(agentId: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<ApiV1DeliveriesGet200Response>>;
    public apiV1DeliveriesGet(agentId: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (agentId === null || agentId === undefined) {
            throw new Error('Required parameter agentId was null or undefined when calling apiV1DeliveriesGet.');
        }

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>agentId, 'agent_id');

        let localVarHeaders = this.defaultHeaders;

        // authentication (bearerAuth) required
        localVarHeaders = this.configuration.addCredentialToHeaders('bearerAuth', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/v1/deliveries`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<ApiV1DeliveriesGet200Response>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

}
