/**
 * Food Delivery Platform API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec, HttpContext 
        }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from '../encoder';
import { Observable }                                        from 'rxjs';

// @ts-ignore
import { ApiV1OrdersOrderIdStatusPut200Response } from '../model/apiV1OrdersOrderIdStatusPut200Response';
// @ts-ignore
import { ApiV1RestaurantsMenuItemIdAvailabilityPutRequest } from '../model/apiV1RestaurantsMenuItemIdAvailabilityPutRequest';
// @ts-ignore
import { ApiV1RestaurantsRestaurantIdMenuGet200Response } from '../model/apiV1RestaurantsRestaurantIdMenuGet200Response';
// @ts-ignore
import { ApiV1RestaurantsRestaurantIdMenuPost201Response } from '../model/apiV1RestaurantsRestaurantIdMenuPost201Response';
// @ts-ignore
import { ApiV1RestaurantsRestaurantIdMenuPostRequest } from '../model/apiV1RestaurantsRestaurantIdMenuPostRequest';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import { BaseService } from '../api.base.service';



@Injectable({
  providedIn: 'root'
})
export class RestaurantsService extends BaseService {

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string|string[], @Optional() configuration?: Configuration) {
        super(basePath, configuration);
    }

    /**
     * Update menu item availability
     * Update the availability status of a menu item
     * @endpoint put /api/v1/restaurants/menu/{itemId}/availability
     * @param itemId 
     * @param apiV1RestaurantsMenuItemIdAvailabilityPutRequest 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiV1RestaurantsMenuItemIdAvailabilityPut(itemId: string, apiV1RestaurantsMenuItemIdAvailabilityPutRequest: ApiV1RestaurantsMenuItemIdAvailabilityPutRequest, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<ApiV1OrdersOrderIdStatusPut200Response>;
    public apiV1RestaurantsMenuItemIdAvailabilityPut(itemId: string, apiV1RestaurantsMenuItemIdAvailabilityPutRequest: ApiV1RestaurantsMenuItemIdAvailabilityPutRequest, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<ApiV1OrdersOrderIdStatusPut200Response>>;
    public apiV1RestaurantsMenuItemIdAvailabilityPut(itemId: string, apiV1RestaurantsMenuItemIdAvailabilityPutRequest: ApiV1RestaurantsMenuItemIdAvailabilityPutRequest, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<ApiV1OrdersOrderIdStatusPut200Response>>;
    public apiV1RestaurantsMenuItemIdAvailabilityPut(itemId: string, apiV1RestaurantsMenuItemIdAvailabilityPutRequest: ApiV1RestaurantsMenuItemIdAvailabilityPutRequest, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (itemId === null || itemId === undefined) {
            throw new Error('Required parameter itemId was null or undefined when calling apiV1RestaurantsMenuItemIdAvailabilityPut.');
        }
        if (apiV1RestaurantsMenuItemIdAvailabilityPutRequest === null || apiV1RestaurantsMenuItemIdAvailabilityPutRequest === undefined) {
            throw new Error('Required parameter apiV1RestaurantsMenuItemIdAvailabilityPutRequest was null or undefined when calling apiV1RestaurantsMenuItemIdAvailabilityPut.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (bearerAuth) required
        localVarHeaders = this.configuration.addCredentialToHeaders('bearerAuth', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/v1/restaurants/menu/${this.configuration.encodeParam({name: "itemId", value: itemId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/availability`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<ApiV1OrdersOrderIdStatusPut200Response>('put', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: apiV1RestaurantsMenuItemIdAvailabilityPutRequest,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get restaurant menu
     * Retrieve the menu items for a specific restaurant
     * @endpoint get /api/v1/restaurants/{restaurantId}/menu
     * @param restaurantId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiV1RestaurantsRestaurantIdMenuGet(restaurantId: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<ApiV1RestaurantsRestaurantIdMenuGet200Response>;
    public apiV1RestaurantsRestaurantIdMenuGet(restaurantId: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<ApiV1RestaurantsRestaurantIdMenuGet200Response>>;
    public apiV1RestaurantsRestaurantIdMenuGet(restaurantId: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<ApiV1RestaurantsRestaurantIdMenuGet200Response>>;
    public apiV1RestaurantsRestaurantIdMenuGet(restaurantId: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (restaurantId === null || restaurantId === undefined) {
            throw new Error('Required parameter restaurantId was null or undefined when calling apiV1RestaurantsRestaurantIdMenuGet.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (bearerAuth) required
        localVarHeaders = this.configuration.addCredentialToHeaders('bearerAuth', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/v1/restaurants/${this.configuration.encodeParam({name: "restaurantId", value: restaurantId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/menu`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<ApiV1RestaurantsRestaurantIdMenuGet200Response>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Add menu item
     * Add a new item to the restaurant menu (Restaurant admin only)
     * @endpoint post /api/v1/restaurants/{restaurantId}/menu
     * @param restaurantId 
     * @param apiV1RestaurantsRestaurantIdMenuPostRequest 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiV1RestaurantsRestaurantIdMenuPost(restaurantId: string, apiV1RestaurantsRestaurantIdMenuPostRequest: ApiV1RestaurantsRestaurantIdMenuPostRequest, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<ApiV1RestaurantsRestaurantIdMenuPost201Response>;
    public apiV1RestaurantsRestaurantIdMenuPost(restaurantId: string, apiV1RestaurantsRestaurantIdMenuPostRequest: ApiV1RestaurantsRestaurantIdMenuPostRequest, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<ApiV1RestaurantsRestaurantIdMenuPost201Response>>;
    public apiV1RestaurantsRestaurantIdMenuPost(restaurantId: string, apiV1RestaurantsRestaurantIdMenuPostRequest: ApiV1RestaurantsRestaurantIdMenuPostRequest, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<ApiV1RestaurantsRestaurantIdMenuPost201Response>>;
    public apiV1RestaurantsRestaurantIdMenuPost(restaurantId: string, apiV1RestaurantsRestaurantIdMenuPostRequest: ApiV1RestaurantsRestaurantIdMenuPostRequest, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (restaurantId === null || restaurantId === undefined) {
            throw new Error('Required parameter restaurantId was null or undefined when calling apiV1RestaurantsRestaurantIdMenuPost.');
        }
        if (apiV1RestaurantsRestaurantIdMenuPostRequest === null || apiV1RestaurantsRestaurantIdMenuPostRequest === undefined) {
            throw new Error('Required parameter apiV1RestaurantsRestaurantIdMenuPostRequest was null or undefined when calling apiV1RestaurantsRestaurantIdMenuPost.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (bearerAuth) required
        localVarHeaders = this.configuration.addCredentialToHeaders('bearerAuth', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/v1/restaurants/${this.configuration.encodeParam({name: "restaurantId", value: restaurantId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/menu`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<ApiV1RestaurantsRestaurantIdMenuPost201Response>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: apiV1RestaurantsRestaurantIdMenuPostRequest,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

}
