/**
 * Food Delivery Platform API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ApiV1OrdersOrderIdStatusPutRequest { 
    status: ApiV1OrdersOrderIdStatusPutRequestStatusEnum;
}
export enum ApiV1OrdersOrderIdStatusPutRequestStatusEnum {
    Confirmed = 'confirmed',
    Preparing = 'preparing',
    Ready = 'ready',
    PickedUp = 'picked_up',
    Delivered = 'delivered',
    Cancelled = 'cancelled'
};



