/**
 * Food Delivery Platform API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ApiV1TrackingOrderIdGet200Response { 
    lat?: number;
    lng?: number;
    timestamp?: string;
}

