/**
 * Food Delivery Platform API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MenuItem } from './menuItem';


export interface ApiV1OrdersPostRequest { 
    user_id: string;
    restaurant_id: string;
    items: Array<MenuItem>;
}

