/**
 * Food Delivery Platform API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ApiV1PaymentsPost200Response { 
    payment_id?: string;
    status?: ApiV1PaymentsPost200ResponseStatusEnum;
}
export enum ApiV1PaymentsPost200ResponseStatusEnum {
    Completed = 'completed',
    Failed = 'failed',
    Pending = 'pending'
};



