/**
 * Food Delivery Platform API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ApiV1DeliveriesDeliveryIdStatusPutRequest { 
    status: ApiV1DeliveriesDeliveryIdStatusPutRequestStatusEnum;
}
export enum ApiV1DeliveriesDeliveryIdStatusPutRequestStatusEnum {
    Assigned = 'assigned',
    PickedUp = 'picked_up',
    EnRoute = 'en_route',
    Delivered = 'delivered',
    Cancelled = 'cancelled'
};



