/**
 * Food Delivery Platform API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ApiV1PaymentsRefundPost200Response { 
    success?: boolean;
    new_balance?: number;
}

