/**
 * Food Delivery Platform API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CircuitBreakersGet200ResponseCircuitBreakersValue { 
    state?: CircuitBreakersGet200ResponseCircuitBreakersValueStateEnum;
    failure_count?: number;
    last_failure_time?: string;
}
export enum CircuitBreakersGet200ResponseCircuitBreakersValueStateEnum {
    Closed = 'closed',
    Open = 'open',
    HalfOpen = 'half_open'
};



