/**
 * Food Delivery Platform API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CircuitBreakersGet200ResponseCircuitBreakersValue } from './circuitBreakersGet200ResponseCircuitBreakersValue';


export interface CircuitBreakersGet200Response { 
    circuit_breakers?: { [key: string]: CircuitBreakersGet200ResponseCircuitBreakersValue; };
    timestamp?: string;
}

