/**
 * Food Delivery Platform API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Delivery { 
    id?: string;
    order_id?: string;
    agent_id?: string;
    status?: DeliveryStatusEnum;
    created_at?: string;
}
export enum DeliveryStatusEnum {
    Assigned = 'assigned',
    PickedUp = 'picked_up',
    EnRoute = 'en_route',
    Delivered = 'delivered',
    Cancelled = 'cancelled'
};



