/**
 * Food Delivery Platform API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Order { 
    id?: string;
    user_id?: string;
    restaurant_id?: string;
    status?: OrderStatusEnum;
    amount?: number;
    created_at?: string;
}
export enum OrderStatusEnum {
    Created = 'created',
    Confirmed = 'confirmed',
    Preparing = 'preparing',
    Ready = 'ready',
    PickedUp = 'picked_up',
    Delivered = 'delivered',
    Cancelled = 'cancelled'
};



