// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.27.2
// source: delivery.proto

package proto

import (
	_ "food-delivery-platform/common/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AssignDeliveryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignDeliveryRequest) Reset() {
	*x = AssignDeliveryRequest{}
	mi := &file_delivery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignDeliveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignDeliveryRequest) ProtoMessage() {}

func (x *AssignDeliveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignDeliveryRequest.ProtoReflect.Descriptor instead.
func (*AssignDeliveryRequest) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{0}
}

func (x *AssignDeliveryRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type AssignDeliveryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignDeliveryResponse) Reset() {
	*x = AssignDeliveryResponse{}
	mi := &file_delivery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignDeliveryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignDeliveryResponse) ProtoMessage() {}

func (x *AssignDeliveryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignDeliveryResponse.ProtoReflect.Descriptor instead.
func (*AssignDeliveryResponse) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{1}
}

func (x *AssignDeliveryResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AssignDeliveryResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type UpdateStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeliveryId    string                 `protobuf:"bytes,1,opt,name=delivery_id,json=deliveryId,proto3" json:"delivery_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStatusRequest) Reset() {
	*x = UpdateStatusRequest{}
	mi := &file_delivery_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatusRequest) ProtoMessage() {}

func (x *UpdateStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateStatusRequest) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateStatusRequest) GetDeliveryId() string {
	if x != nil {
		return x.DeliveryId
	}
	return ""
}

func (x *UpdateStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdateStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStatusResponse) Reset() {
	*x = UpdateStatusResponse{}
	mi := &file_delivery_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatusResponse) ProtoMessage() {}

func (x *UpdateStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateStatusResponse) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateStatusResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetDeliveriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeliveriesRequest) Reset() {
	*x = GetDeliveriesRequest{}
	mi := &file_delivery_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeliveriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeliveriesRequest) ProtoMessage() {}

func (x *GetDeliveriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeliveriesRequest.ProtoReflect.Descriptor instead.
func (*GetDeliveriesRequest) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{4}
}

func (x *GetDeliveriesRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type GetDeliveriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deliveries    []*Delivery            `protobuf:"bytes,1,rep,name=deliveries,proto3" json:"deliveries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeliveriesResponse) Reset() {
	*x = GetDeliveriesResponse{}
	mi := &file_delivery_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeliveriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeliveriesResponse) ProtoMessage() {}

func (x *GetDeliveriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeliveriesResponse.ProtoReflect.Descriptor instead.
func (*GetDeliveriesResponse) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{5}
}

func (x *GetDeliveriesResponse) GetDeliveries() []*Delivery {
	if x != nil {
		return x.Deliveries
	}
	return nil
}

type Delivery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Delivery) Reset() {
	*x = Delivery{}
	mi := &file_delivery_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Delivery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Delivery) ProtoMessage() {}

func (x *Delivery) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Delivery.ProtoReflect.Descriptor instead.
func (*Delivery) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{6}
}

func (x *Delivery) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Delivery) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *Delivery) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Delivery) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_delivery_proto protoreflect.FileDescriptor

const file_delivery_proto_rawDesc = "" +
	"\n" +
	"\x0edelivery.proto\x12\bdelivery\x1a\fcommon.proto\"2\n" +
	"\x15AssignDeliveryRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"I\n" +
	"\x16AssignDeliveryResponse\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"N\n" +
	"\x13UpdateStatusRequest\x12\x1f\n" +
	"\vdelivery_id\x18\x01 \x01(\tR\n" +
	"deliveryId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"F\n" +
	"\x14UpdateStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"1\n" +
	"\x14GetDeliveriesRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"K\n" +
	"\x15GetDeliveriesResponse\x122\n" +
	"\n" +
	"deliveries\x18\x01 \x03(\v2\x12.delivery.DeliveryR\n" +
	"deliveries\"h\n" +
	"\bDelivery\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status2\x87\x02\n" +
	"\x0fDeliveryService\x12S\n" +
	"\x0eAssignDelivery\x12\x1f.delivery.AssignDeliveryRequest\x1a .delivery.AssignDeliveryResponse\x12M\n" +
	"\fUpdateStatus\x12\x1d.delivery.UpdateStatusRequest\x1a\x1e.delivery.UpdateStatusResponse\x12P\n" +
	"\rGetDeliveries\x12\x1e.delivery.GetDeliveriesRequest\x1a\x1f.delivery.GetDeliveriesResponseBAZ?food-delivery-platform/services/delivery-service/internal/protob\x06proto3"

var (
	file_delivery_proto_rawDescOnce sync.Once
	file_delivery_proto_rawDescData []byte
)

func file_delivery_proto_rawDescGZIP() []byte {
	file_delivery_proto_rawDescOnce.Do(func() {
		file_delivery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_delivery_proto_rawDesc), len(file_delivery_proto_rawDesc)))
	})
	return file_delivery_proto_rawDescData
}

var file_delivery_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_delivery_proto_goTypes = []any{
	(*AssignDeliveryRequest)(nil),  // 0: delivery.AssignDeliveryRequest
	(*AssignDeliveryResponse)(nil), // 1: delivery.AssignDeliveryResponse
	(*UpdateStatusRequest)(nil),    // 2: delivery.UpdateStatusRequest
	(*UpdateStatusResponse)(nil),   // 3: delivery.UpdateStatusResponse
	(*GetDeliveriesRequest)(nil),   // 4: delivery.GetDeliveriesRequest
	(*GetDeliveriesResponse)(nil),  // 5: delivery.GetDeliveriesResponse
	(*Delivery)(nil),               // 6: delivery.Delivery
}
var file_delivery_proto_depIdxs = []int32{
	6, // 0: delivery.GetDeliveriesResponse.deliveries:type_name -> delivery.Delivery
	0, // 1: delivery.DeliveryService.AssignDelivery:input_type -> delivery.AssignDeliveryRequest
	2, // 2: delivery.DeliveryService.UpdateStatus:input_type -> delivery.UpdateStatusRequest
	4, // 3: delivery.DeliveryService.GetDeliveries:input_type -> delivery.GetDeliveriesRequest
	1, // 4: delivery.DeliveryService.AssignDelivery:output_type -> delivery.AssignDeliveryResponse
	3, // 5: delivery.DeliveryService.UpdateStatus:output_type -> delivery.UpdateStatusResponse
	5, // 6: delivery.DeliveryService.GetDeliveries:output_type -> delivery.GetDeliveriesResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_delivery_proto_init() }
func file_delivery_proto_init() {
	if File_delivery_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_delivery_proto_rawDesc), len(file_delivery_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_delivery_proto_goTypes,
		DependencyIndexes: file_delivery_proto_depIdxs,
		MessageInfos:      file_delivery_proto_msgTypes,
	}.Build()
	File_delivery_proto = out.File
	file_delivery_proto_goTypes = nil
	file_delivery_proto_depIdxs = nil
}
