apiVersion: v1
kind: Service
metadata:
  name: tracking-service
  labels:
    app: tracking-service
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: tracking-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracking-service
spec:
  selector:
    matchLabels:
      app: tracking-service
  replicas: 1
  template:
    metadata:
      labels:
        app: tracking-service
    spec:
      containers:
      - name: tracking-service
        image: food-delivery/tracking-service:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: DB_HOST
          value: "postgres"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          value: "root"
        - name: DB_NAME
          value: "fooddb"
        - name: KAFKA_BROKERS
          value: "kafka:9092"
        - name: JAEGER_ENDPOINT
          value: "http://jaeger:14268/api/traces"
        ports:
        - containerPort: 8080
          name: http
