// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.2
// source: tracking.proto

package proto

import (
	context "context"
	proto "food-delivery-platform/common/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TrackingService_TrackDelivery_FullMethodName = "/tracking.TrackingService/TrackDelivery"
	TrackingService_SendLocation_FullMethodName  = "/tracking.TrackingService/SendLocation"
)

// TrackingServiceClient is the client API for TrackingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TrackingServiceClient interface {
	TrackDelivery(ctx context.Context, in *TrackDeliveryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[proto.Location], error)
	SendLocation(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[proto.Location, TrackingResponse], error)
}

type trackingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTrackingServiceClient(cc grpc.ClientConnInterface) TrackingServiceClient {
	return &trackingServiceClient{cc}
}

func (c *trackingServiceClient) TrackDelivery(ctx context.Context, in *TrackDeliveryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[proto.Location], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TrackingService_ServiceDesc.Streams[0], TrackingService_TrackDelivery_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TrackDeliveryRequest, proto.Location]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TrackingService_TrackDeliveryClient = grpc.ServerStreamingClient[proto.Location]

func (c *trackingServiceClient) SendLocation(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[proto.Location, TrackingResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TrackingService_ServiceDesc.Streams[1], TrackingService_SendLocation_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[proto.Location, TrackingResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TrackingService_SendLocationClient = grpc.ClientStreamingClient[proto.Location, TrackingResponse]

// TrackingServiceServer is the server API for TrackingService service.
// All implementations must embed UnimplementedTrackingServiceServer
// for forward compatibility.
type TrackingServiceServer interface {
	TrackDelivery(*TrackDeliveryRequest, grpc.ServerStreamingServer[proto.Location]) error
	SendLocation(grpc.ClientStreamingServer[proto.Location, TrackingResponse]) error
	mustEmbedUnimplementedTrackingServiceServer()
}

// UnimplementedTrackingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTrackingServiceServer struct{}

func (UnimplementedTrackingServiceServer) TrackDelivery(*TrackDeliveryRequest, grpc.ServerStreamingServer[proto.Location]) error {
	return status.Errorf(codes.Unimplemented, "method TrackDelivery not implemented")
}
func (UnimplementedTrackingServiceServer) SendLocation(grpc.ClientStreamingServer[proto.Location, TrackingResponse]) error {
	return status.Errorf(codes.Unimplemented, "method SendLocation not implemented")
}
func (UnimplementedTrackingServiceServer) mustEmbedUnimplementedTrackingServiceServer() {}
func (UnimplementedTrackingServiceServer) testEmbeddedByValue()                         {}

// UnsafeTrackingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TrackingServiceServer will
// result in compilation errors.
type UnsafeTrackingServiceServer interface {
	mustEmbedUnimplementedTrackingServiceServer()
}

func RegisterTrackingServiceServer(s grpc.ServiceRegistrar, srv TrackingServiceServer) {
	// If the following call pancis, it indicates UnimplementedTrackingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TrackingService_ServiceDesc, srv)
}

func _TrackingService_TrackDelivery_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TrackDeliveryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TrackingServiceServer).TrackDelivery(m, &grpc.GenericServerStream[TrackDeliveryRequest, proto.Location]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TrackingService_TrackDeliveryServer = grpc.ServerStreamingServer[proto.Location]

func _TrackingService_SendLocation_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TrackingServiceServer).SendLocation(&grpc.GenericServerStream[proto.Location, TrackingResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TrackingService_SendLocationServer = grpc.ClientStreamingServer[proto.Location, TrackingResponse]

// TrackingService_ServiceDesc is the grpc.ServiceDesc for TrackingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TrackingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tracking.TrackingService",
	HandlerType: (*TrackingServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TrackDelivery",
			Handler:       _TrackingService_TrackDelivery_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SendLocation",
			Handler:       _TrackingService_SendLocation_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "tracking.proto",
}
