// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.27.2
// source: tracking.proto

package proto

import (
	proto "food-delivery-platform/common/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TrackDeliveryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackDeliveryRequest) Reset() {
	*x = TrackDeliveryRequest{}
	mi := &file_tracking_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackDeliveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackDeliveryRequest) ProtoMessage() {}

func (x *TrackDeliveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tracking_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackDeliveryRequest.ProtoReflect.Descriptor instead.
func (*TrackDeliveryRequest) Descriptor() ([]byte, []int) {
	return file_tracking_proto_rawDescGZIP(), []int{0}
}

func (x *TrackDeliveryRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type TrackingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackingResponse) Reset() {
	*x = TrackingResponse{}
	mi := &file_tracking_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackingResponse) ProtoMessage() {}

func (x *TrackingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tracking_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackingResponse.ProtoReflect.Descriptor instead.
func (*TrackingResponse) Descriptor() ([]byte, []int) {
	return file_tracking_proto_rawDescGZIP(), []int{1}
}

func (x *TrackingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_tracking_proto protoreflect.FileDescriptor

const file_tracking_proto_rawDesc = "" +
	"\n" +
	"\x0etracking.proto\x12\btracking\x1a\fcommon.proto\"1\n" +
	"\x14TrackDeliveryRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\",\n" +
	"\x10TrackingResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\x96\x01\n" +
	"\x0fTrackingService\x12C\n" +
	"\rTrackDelivery\x12\x1e.tracking.TrackDeliveryRequest\x1a\x10.common.Location0\x01\x12>\n" +
	"\fSendLocation\x12\x10.common.Location\x1a\x1a.tracking.TrackingResponse(\x01B\x10Z\x0einternal/protob\x06proto3"

var (
	file_tracking_proto_rawDescOnce sync.Once
	file_tracking_proto_rawDescData []byte
)

func file_tracking_proto_rawDescGZIP() []byte {
	file_tracking_proto_rawDescOnce.Do(func() {
		file_tracking_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tracking_proto_rawDesc), len(file_tracking_proto_rawDesc)))
	})
	return file_tracking_proto_rawDescData
}

var file_tracking_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_tracking_proto_goTypes = []any{
	(*TrackDeliveryRequest)(nil), // 0: tracking.TrackDeliveryRequest
	(*TrackingResponse)(nil),     // 1: tracking.TrackingResponse
	(*proto.Location)(nil),       // 2: common.Location
}
var file_tracking_proto_depIdxs = []int32{
	0, // 0: tracking.TrackingService.TrackDelivery:input_type -> tracking.TrackDeliveryRequest
	2, // 1: tracking.TrackingService.SendLocation:input_type -> common.Location
	2, // 2: tracking.TrackingService.TrackDelivery:output_type -> common.Location
	1, // 3: tracking.TrackingService.SendLocation:output_type -> tracking.TrackingResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tracking_proto_init() }
func file_tracking_proto_init() {
	if File_tracking_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tracking_proto_rawDesc), len(file_tracking_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tracking_proto_goTypes,
		DependencyIndexes: file_tracking_proto_depIdxs,
		MessageInfos:      file_tracking_proto_msgTypes,
	}.Build()
	File_tracking_proto = out.File
	file_tracking_proto_goTypes = nil
	file_tracking_proto_depIdxs = nil
}
